'use strict';

/*module.exports.blacklist = [
    'Pnau',
    'Lorde',
    'Clean Bandit',
    'Bliss n Eso',
    'Calvin Harris',
    'Maroon 5',
    'Mura Masa',
    'Nevada',
    'Snakehips',
    'Robin Schulz',
    'Jon Bellion',
    'Starley',
    'The Chainsmokers',
    'Cheat Codes',
    'Sofi Tukker',
    'Peking Duk',
    'Martin Jensen',
    'The Vamps',
    'ODESZA',
    'Isaiah',
    'Ed Sheeran',
    'Flume',
    'Naughty Boy',
    'Martin Solveig',
    'Mr. Probz',
    'L D R U',
    'Chance The Rapper',
    'Bebe Rexha',
    'Rudimental',
    'Dillon Francis',
    'Zara Larsson',
    'Tom Jay Williams',
    'Martin Garrix',
    'Steve Aoki',
    'Ed Sheeran',
    'PON CHO',
    'FRENSHIP',
    'Drake',
    'Bruno Mars',
    'Jax Jones',
    'NERVO',
    'Milky Chance',
    'Vice',
    'Sage The Gemini',
    'San Holo',
    'Olivia Holt',
    'Katy Perry',
    'Cosmo\'s Midnight',
    'Gryffin',
    'Marky Style',
    'Robot Heart',
];*/
module.exports.blacklist = [
    'Bruno Mars',
    'Ed Sheeran',
    'Maroon 5',
];
